sudo: required

language: bash

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=emurgornd/jormungandr

script:
  - docker build -t $DOCKER_IMAGE .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      DOCKER_IMAGE_COMMIT=$(git log -1 --pretty=format:'%h');
      DOCKER_IMAGE_TIMESTAMP=$(docker inspect -f '{{ .Created }}' ${DOCKER_IMAGE}|awk -F':' '{print $1$2}'|sed 's%-\|T%%g');
      DOCKER_IMAGE_JORMUNGANDR_VERSION=$(docker inspect --format "{{ index .Config.Labels \"jormungandr.version\"}}");
      docker tag ${DOCKER_IMAGE}:latest ${DOCKER_IMAGE}:${DOCKER_IMAGE_TIMESTAMP}-${JORMUNGANDR_VERSION}-${DOCKER_IMAGE_COMMIT};
      docker push ${DOCKER_IMAGE}:latest;
      docker push ${DOCKER_IMAGE}:${DOCKER_IMAGE_TIMESTAMP}-${JORMUNGANDR_VERSION}-${DOCKER_IMAGE_COMMIT};
    fi

#notifications:
#  email:
#    recipients:
#      - nil@null.com
#    on_success: always
#    on_failure: always
