FROM alpine AS src
RUN apk add --no-cache git
ARG JORMUNGANDR_COMMIT=v0.7.5
ENV JORMUNGANDR_COMMIT ${JORMUNGANDR_COMMIT}

RUN git clone https://github.com/input-output-hk/jormungandr /src && \
    cd /src && \
    git checkout $JORMUNGANDR_COMMIT && \
    git submodule init && \
    git submodule update --recursive
